/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RsvpTokenRouteImport } from './routes/rsvp/$token'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthApplyRouteImport } from './routes/_auth/apply'
import { Route as AuthenticatedLayoutIndexRouteImport } from './routes/_authenticated/_layout/index'
import { Route as AuthenticatedLayoutSettingsRouteImport } from './routes/_authenticated/_layout/settings'
import { Route as AuthenticatedLayoutRegisterRouteImport } from './routes/_authenticated/_layout/register'
import { Route as AuthenticatedLayoutProjectsRouteImport } from './routes/_authenticated/_layout/projects'
import { Route as AuthenticatedLayoutMonitoringRouteImport } from './routes/_authenticated/_layout/monitoring'
import { Route as AuthenticatedLayoutGraphRouteImport } from './routes/_authenticated/_layout/graph'
import { Route as AuthenticatedLayoutChatRouteImport } from './routes/_authenticated/_layout/chat'
import { Route as AuthenticatedLayoutVendorsIndexRouteImport } from './routes/_authenticated/_layout/vendors/index'
import { Route as AuthenticatedLayoutMembersIndexRouteImport } from './routes/_authenticated/_layout/members/index'
import { Route as AuthenticatedLayoutEventsIndexRouteImport } from './routes/_authenticated/_layout/events/index'
import { Route as AuthenticatedLayoutVendorsVendorIdRouteImport } from './routes/_authenticated/_layout/vendors/$vendorId'
import { Route as AuthenticatedLayoutMembersMemberIdRouteImport } from './routes/_authenticated/_layout/members/$memberId'
import { Route as AuthenticatedLayoutEventsEventIdRouteImport } from './routes/_authenticated/_layout/events/$eventId'
import { Route as AuthenticatedLayoutAdminVendorsNewRouteImport } from './routes/_authenticated/_layout/admin/vendors/new'
import { Route as AuthenticatedLayoutAdminEventsNewRouteImport } from './routes/_authenticated/_layout/admin/events/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthApplyRoute = AuthApplyRouteImport.update({
  id: '/_auth/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutSettingsRoute =
  AuthenticatedLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutRegisterRoute =
  AuthenticatedLayoutRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutProjectsRoute =
  AuthenticatedLayoutProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMonitoringRoute =
  AuthenticatedLayoutMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutGraphRoute =
  AuthenticatedLayoutGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutChatRoute = AuthenticatedLayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)
const AuthenticatedLayoutVendorsIndexRoute =
  AuthenticatedLayoutVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMembersIndexRoute =
  AuthenticatedLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutEventsIndexRoute =
  AuthenticatedLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutVendorsVendorIdRoute =
  AuthenticatedLayoutVendorsVendorIdRouteImport.update({
    id: '/vendors/$vendorId',
    path: '/vendors/$vendorId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMembersMemberIdRoute =
  AuthenticatedLayoutMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutEventsEventIdRoute =
  AuthenticatedLayoutEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAdminVendorsNewRoute =
  AuthenticatedLayoutAdminVendorsNewRouteImport.update({
    id: '/admin/vendors/new',
    path: '/admin/vendors/new',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAdminEventsNewRoute =
  AuthenticatedLayoutAdminEventsNewRouteImport.update({
    id: '/admin/events/new',
    path: '/admin/events/new',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedLayoutIndexRoute
  '/apply': typeof AuthApplyRoute
  '/signin': typeof AuthSigninRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/chat': typeof AuthenticatedLayoutChatRoute
  '/graph': typeof AuthenticatedLayoutGraphRoute
  '/monitoring': typeof AuthenticatedLayoutMonitoringRoute
  '/projects': typeof AuthenticatedLayoutProjectsRoute
  '/register': typeof AuthenticatedLayoutRegisterRoute
  '/settings': typeof AuthenticatedLayoutSettingsRoute
  '/events/$eventId': typeof AuthenticatedLayoutEventsEventIdRoute
  '/members/$memberId': typeof AuthenticatedLayoutMembersMemberIdRoute
  '/vendors/$vendorId': typeof AuthenticatedLayoutVendorsVendorIdRoute
  '/events/': typeof AuthenticatedLayoutEventsIndexRoute
  '/members/': typeof AuthenticatedLayoutMembersIndexRoute
  '/vendors/': typeof AuthenticatedLayoutVendorsIndexRoute
  '/admin/events/new': typeof AuthenticatedLayoutAdminEventsNewRoute
  '/admin/vendors/new': typeof AuthenticatedLayoutAdminVendorsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedLayoutIndexRoute
  '/apply': typeof AuthApplyRoute
  '/signin': typeof AuthSigninRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/chat': typeof AuthenticatedLayoutChatRoute
  '/graph': typeof AuthenticatedLayoutGraphRoute
  '/monitoring': typeof AuthenticatedLayoutMonitoringRoute
  '/projects': typeof AuthenticatedLayoutProjectsRoute
  '/register': typeof AuthenticatedLayoutRegisterRoute
  '/settings': typeof AuthenticatedLayoutSettingsRoute
  '/events/$eventId': typeof AuthenticatedLayoutEventsEventIdRoute
  '/members/$memberId': typeof AuthenticatedLayoutMembersMemberIdRoute
  '/vendors/$vendorId': typeof AuthenticatedLayoutVendorsVendorIdRoute
  '/events': typeof AuthenticatedLayoutEventsIndexRoute
  '/members': typeof AuthenticatedLayoutMembersIndexRoute
  '/vendors': typeof AuthenticatedLayoutVendorsIndexRoute
  '/admin/events/new': typeof AuthenticatedLayoutAdminEventsNewRoute
  '/admin/vendors/new': typeof AuthenticatedLayoutAdminVendorsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/apply': typeof AuthApplyRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/rsvp/$token': typeof RsvpTokenRoute
  '/_authenticated/_layout/chat': typeof AuthenticatedLayoutChatRoute
  '/_authenticated/_layout/graph': typeof AuthenticatedLayoutGraphRoute
  '/_authenticated/_layout/monitoring': typeof AuthenticatedLayoutMonitoringRoute
  '/_authenticated/_layout/projects': typeof AuthenticatedLayoutProjectsRoute
  '/_authenticated/_layout/register': typeof AuthenticatedLayoutRegisterRoute
  '/_authenticated/_layout/settings': typeof AuthenticatedLayoutSettingsRoute
  '/_authenticated/_layout/': typeof AuthenticatedLayoutIndexRoute
  '/_authenticated/_layout/events/$eventId': typeof AuthenticatedLayoutEventsEventIdRoute
  '/_authenticated/_layout/members/$memberId': typeof AuthenticatedLayoutMembersMemberIdRoute
  '/_authenticated/_layout/vendors/$vendorId': typeof AuthenticatedLayoutVendorsVendorIdRoute
  '/_authenticated/_layout/events/': typeof AuthenticatedLayoutEventsIndexRoute
  '/_authenticated/_layout/members/': typeof AuthenticatedLayoutMembersIndexRoute
  '/_authenticated/_layout/vendors/': typeof AuthenticatedLayoutVendorsIndexRoute
  '/_authenticated/_layout/admin/events/new': typeof AuthenticatedLayoutAdminEventsNewRoute
  '/_authenticated/_layout/admin/vendors/new': typeof AuthenticatedLayoutAdminVendorsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/signin'
    | '/rsvp/$token'
    | '/chat'
    | '/graph'
    | '/monitoring'
    | '/projects'
    | '/register'
    | '/settings'
    | '/events/$eventId'
    | '/members/$memberId'
    | '/vendors/$vendorId'
    | '/events/'
    | '/members/'
    | '/vendors/'
    | '/admin/events/new'
    | '/admin/vendors/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/signin'
    | '/rsvp/$token'
    | '/chat'
    | '/graph'
    | '/monitoring'
    | '/projects'
    | '/register'
    | '/settings'
    | '/events/$eventId'
    | '/members/$memberId'
    | '/vendors/$vendorId'
    | '/events'
    | '/members'
    | '/vendors'
    | '/admin/events/new'
    | '/admin/vendors/new'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_auth/apply'
    | '/_auth/signin'
    | '/_authenticated/_layout'
    | '/rsvp/$token'
    | '/_authenticated/_layout/chat'
    | '/_authenticated/_layout/graph'
    | '/_authenticated/_layout/monitoring'
    | '/_authenticated/_layout/projects'
    | '/_authenticated/_layout/register'
    | '/_authenticated/_layout/settings'
    | '/_authenticated/_layout/'
    | '/_authenticated/_layout/events/$eventId'
    | '/_authenticated/_layout/members/$memberId'
    | '/_authenticated/_layout/vendors/$vendorId'
    | '/_authenticated/_layout/events/'
    | '/_authenticated/_layout/members/'
    | '/_authenticated/_layout/vendors/'
    | '/_authenticated/_layout/admin/events/new'
    | '/_authenticated/_layout/admin/vendors/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthApplyRoute: typeof AuthApplyRoute
  AuthSigninRoute: typeof AuthSigninRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/apply': {
      id: '/_auth/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/settings': {
      id: '/_authenticated/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedLayoutSettingsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/register': {
      id: '/_authenticated/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedLayoutRegisterRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/projects': {
      id: '/_authenticated/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedLayoutProjectsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/monitoring': {
      id: '/_authenticated/_layout/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedLayoutMonitoringRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/graph': {
      id: '/_authenticated/_layout/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedLayoutGraphRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/chat': {
      id: '/_authenticated/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedLayoutChatRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/vendors/': {
      id: '/_authenticated/_layout/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedLayoutVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/members/': {
      id: '/_authenticated/_layout/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedLayoutMembersIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/events/': {
      id: '/_authenticated/_layout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedLayoutEventsIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/vendors/$vendorId': {
      id: '/_authenticated/_layout/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof AuthenticatedLayoutVendorsVendorIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/members/$memberId': {
      id: '/_authenticated/_layout/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/members/$memberId'
      preLoaderRoute: typeof AuthenticatedLayoutMembersMemberIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/events/$eventId': {
      id: '/_authenticated/_layout/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedLayoutEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/admin/vendors/new': {
      id: '/_authenticated/_layout/admin/vendors/new'
      path: '/admin/vendors/new'
      fullPath: '/admin/vendors/new'
      preLoaderRoute: typeof AuthenticatedLayoutAdminVendorsNewRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/admin/events/new': {
      id: '/_authenticated/_layout/admin/events/new'
      path: '/admin/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AuthenticatedLayoutAdminEventsNewRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutChatRoute: typeof AuthenticatedLayoutChatRoute
  AuthenticatedLayoutGraphRoute: typeof AuthenticatedLayoutGraphRoute
  AuthenticatedLayoutMonitoringRoute: typeof AuthenticatedLayoutMonitoringRoute
  AuthenticatedLayoutProjectsRoute: typeof AuthenticatedLayoutProjectsRoute
  AuthenticatedLayoutRegisterRoute: typeof AuthenticatedLayoutRegisterRoute
  AuthenticatedLayoutSettingsRoute: typeof AuthenticatedLayoutSettingsRoute
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
  AuthenticatedLayoutEventsEventIdRoute: typeof AuthenticatedLayoutEventsEventIdRoute
  AuthenticatedLayoutMembersMemberIdRoute: typeof AuthenticatedLayoutMembersMemberIdRoute
  AuthenticatedLayoutVendorsVendorIdRoute: typeof AuthenticatedLayoutVendorsVendorIdRoute
  AuthenticatedLayoutEventsIndexRoute: typeof AuthenticatedLayoutEventsIndexRoute
  AuthenticatedLayoutMembersIndexRoute: typeof AuthenticatedLayoutMembersIndexRoute
  AuthenticatedLayoutVendorsIndexRoute: typeof AuthenticatedLayoutVendorsIndexRoute
  AuthenticatedLayoutAdminEventsNewRoute: typeof AuthenticatedLayoutAdminEventsNewRoute
  AuthenticatedLayoutAdminVendorsNewRoute: typeof AuthenticatedLayoutAdminVendorsNewRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutChatRoute: AuthenticatedLayoutChatRoute,
  AuthenticatedLayoutGraphRoute: AuthenticatedLayoutGraphRoute,
  AuthenticatedLayoutMonitoringRoute: AuthenticatedLayoutMonitoringRoute,
  AuthenticatedLayoutProjectsRoute: AuthenticatedLayoutProjectsRoute,
  AuthenticatedLayoutRegisterRoute: AuthenticatedLayoutRegisterRoute,
  AuthenticatedLayoutSettingsRoute: AuthenticatedLayoutSettingsRoute,
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
  AuthenticatedLayoutEventsEventIdRoute: AuthenticatedLayoutEventsEventIdRoute,
  AuthenticatedLayoutMembersMemberIdRoute:
    AuthenticatedLayoutMembersMemberIdRoute,
  AuthenticatedLayoutVendorsVendorIdRoute:
    AuthenticatedLayoutVendorsVendorIdRoute,
  AuthenticatedLayoutEventsIndexRoute: AuthenticatedLayoutEventsIndexRoute,
  AuthenticatedLayoutMembersIndexRoute: AuthenticatedLayoutMembersIndexRoute,
  AuthenticatedLayoutVendorsIndexRoute: AuthenticatedLayoutVendorsIndexRoute,
  AuthenticatedLayoutAdminEventsNewRoute:
    AuthenticatedLayoutAdminEventsNewRoute,
  AuthenticatedLayoutAdminVendorsNewRoute:
    AuthenticatedLayoutAdminVendorsNewRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthApplyRoute: AuthApplyRoute,
  AuthSigninRoute: AuthSigninRoute,
  RsvpTokenRoute: RsvpTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
